# Generated by Django 2.2 on 2022-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudoku_dimensions_field', models.IntegerField()),
                ('sudoku_dimensions_house', models.IntegerField()),
                ('sudoku_state', models.CharField(max_length=500)),
            ],
        ),
    ]
