# Generated by Django 2.2 on 2022-03-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_savedsudoku_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuBlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('is_registered_user', models.BooleanField()),
                ('password_salt', models.CharField(max_length=8)),
                ('password_hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField()),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoku.SudokuBlogUser')),
                ('saved_sudoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoku.SavedSudoku')),
            ],
        ),
    ]
