# Generated by Django 2.2 on 2022-03-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_sudokubloguser_sudokucomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsudoku',
            name='sudoku_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sudoku.SudokuBlogUser'),
            preserve_default=False,
        ),
    ]
